<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TariffRegionBehindTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tariff_region_behind')->delete();
        
        \DB::table('tariff_region_behind')->insert(array (
            0 => 
            array (
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '35.00',
                'price_min' => '35.00',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 22,
                'tariff_region_behind_id' => 2,
                'tariff_region_id' => 14,
                'updated_at' => NULL,
                'zone_distance' => 30.0,
            ),
            1 => 
            array (
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '20.00',
                'price_min' => '20.00',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 24,
                'tariff_region_behind_id' => 4,
                'tariff_region_id' => 16,
                'updated_at' => NULL,
                'zone_distance' => 30.0,
            ),
            2 => 
            array (
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '18.00',
                'price_min' => '14.00',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 25,
                'tariff_region_behind_id' => 5,
                'tariff_region_id' => 17,
                'updated_at' => NULL,
                'zone_distance' => 30.0,
            ),
            3 => 
            array (
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '15.00',
                'price_min' => '17.00',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 26,
                'tariff_region_behind_id' => 6,
                'tariff_region_id' => 18,
                'updated_at' => NULL,
                'zone_distance' => 30.0,
            ),
            4 => 
            array (
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '25.00',
                'price_min' => '13.00',
                'price_type_id' => 3,
                'sit_fix_price' => '380.00',
                'sit_price_km' => '25.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 4,
                'sitting_fee' => 1,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 27,
                'tariff_region_behind_id' => 7,
                'tariff_region_id' => 19,
                'updated_at' => NULL,
                'zone_distance' => 30.0,
            ),
            5 => 
            array (
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '40.00',
                'price_min' => '20.00',
                'price_type_id' => 3,
                'sit_fix_price' => '680.00',
                'sit_price_km' => '40.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 4,
                'sitting_fee' => 1,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 28,
                'tariff_region_behind_id' => 8,
                'tariff_region_id' => 20,
                'updated_at' => NULL,
                'zone_distance' => 35.0,
            ),
            6 => 
            array (
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '80.00',
                'price_min' => '15.00',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 12,
                'tariff_region_behind_id' => 9,
                'tariff_region_id' => 1,
                'updated_at' => NULL,
                'zone_distance' => 15.0,
            ),
            7 => 
            array (
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '100.00',
                'price_min' => '20.00',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 13,
                'tariff_region_behind_id' => 10,
                'tariff_region_id' => 2,
                'updated_at' => NULL,
                'zone_distance' => 15.0,
            ),
            8 => 
            array (
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '200.00',
                'price_min' => '60.00',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 14,
                'tariff_region_behind_id' => 11,
                'tariff_region_id' => 3,
                'updated_at' => NULL,
                'zone_distance' => 15.0,
            ),
            9 => 
            array (
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '120.00',
                'price_min' => '30.00',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 15,
                'tariff_region_behind_id' => 12,
                'tariff_region_id' => 4,
                'updated_at' => NULL,
                'zone_distance' => 15.0,
            ),
            10 => 
            array (
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '19.30',
                'price_min' => '16.53',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '17.54',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 1,
                'sitting_fee' => 1,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 85,
                'tariff_region_behind_id' => 13,
                'tariff_region_id' => 21,
                'updated_at' => NULL,
                'zone_distance' => 50.0,
            ),
            11 => 
            array (
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '27.57',
                'price_min' => '29.70',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '36.73',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 1,
                'sitting_fee' => 1,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 86,
                'tariff_region_behind_id' => 14,
                'tariff_region_id' => 22,
                'updated_at' => NULL,
                'zone_distance' => 50.0,
            ),
        ));
        
        
    }
}