<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TariffRegionsCitiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tariff_regions_cities')->delete();
        
        \DB::table('tariff_regions_cities')->insert(array (
            0 => 
            array (
                'area_id' => 24,
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => 0,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => 1,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => '1.00',
                'price_km' => '50.00',
                'price_min' => '30.00',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 12,
                'tariff_region_city_id' => 1,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'area_id' => 24,
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => 0,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => 1,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => '1.00',
                'price_km' => '120.49',
                'price_min' => '300.55',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 13,
                'tariff_region_city_id' => 2,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'area_id' => 24,
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => 0,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => 1,
                'merge_km_minute' => 0,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 1,
                'paid_wait_stop_minute' => '10.00',
                'price_km' => '180.00',
                'price_min' => '60.00',
                'price_type_id' => 1,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 14,
                'tariff_region_city_id' => 3,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'area_id' => 24,
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => 0,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '200.00',
                'price_min' => '50.00',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 15,
                'tariff_region_city_id' => 4,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'area_id' => 1,
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => 0,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => 1,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => '15.00',
                'price_km' => '20.00',
                'price_min' => '20.00',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 22,
                'tariff_region_city_id' => 14,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'area_id' => 1,
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => 0,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => 1,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => '25.00',
                'price_km' => '15.00',
                'price_min' => '15.00',
                'price_type_id' => 3,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 24,
                'tariff_region_city_id' => 16,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'area_id' => 1,
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 40,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '0.00',
                'price_min' => '14.00',
                'price_type_id' => 1,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 25,
                'tariff_region_city_id' => 17,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'area_id' => 1,
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => 0,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 30,
                'paid_wait_stop_minute' => '15.00',
                'price_km' => '0.00',
                'price_min' => '15.00',
                'price_type_id' => 1,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 26,
                'tariff_region_city_id' => 18,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'area_id' => 1,
                'cancel_fee' => '1.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '18.00',
                'price_min' => '13.00',
                'price_type_id' => 3,
                'sit_fix_price' => '380.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 27,
                'tariff_region_city_id' => 19,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'area_id' => 1,
                'cancel_fee' => '1.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 1,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '20.00',
                'price_min' => '30.00',
                'price_type_id' => 3,
                'sit_fix_price' => '680.00',
                'sit_price_km' => '25.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 4,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 28,
                'tariff_region_city_id' => 20,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'area_id' => 1,
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 0,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 30,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '0.00',
                'price_min' => '16.53',
                'price_type_id' => 1,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 85,
                'tariff_region_city_id' => 21,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'area_id' => 1,
                'cancel_fee' => '0.00',
                'change_initial_price_percent' => NULL,
                'created_at' => NULL,
                'enable_speed_wait' => 0,
                'free_wait_stop_minutes' => NULL,
                'merge_km_minute' => 0,
                'minimal_distance_value' => 0.0,
                'minimal_duration_value' => 0,
                'paid_wait_stop_minute' => NULL,
                'price_km' => '0.00',
                'price_min' => '29.70',
                'price_type_id' => 1,
                'sit_fix_price' => '0.00',
                'sit_price_km' => '0.00',
                'sit_price_minute' => '0.00',
                'sit_type_id' => 3,
                'sitting_fee' => 0,
                'speed_wait_limit' => 0,
                'speed_wait_price_minute' => '0.00',
                'tariff_id' => 86,
                'tariff_region_city_id' => 22,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}